[package]

name = "rust_example"
version = "0.0.1"
authors = ["Steve Klabnik <steve@steveklabnik.com>"]

[lib]
name = "rust_example"
crate_type = ["staticlib"]

[dependencies.rlibc]
git = "https://github.com/rust-lang/rlibc"
